name: Python Selenium

on:
  push:
    paths:
      - python-selenium/Dockerfile
    branches:
      - master
  workflow_run:
    types:
      - completed
    workflows:
      - Python
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-push:
    permissions:
      contents: read
      packages: write
    strategy:
        matrix:
            python_version: [3.12, 3.13]
    uses: ./.github/workflows/build-and-push.yaml
    with:
        tag: python${{ matrix.python_version }}-selenium
        context: python-selenium
        platforms: linux/arm64
        base_image: ghcr.io/isaacasancheza/lambda-images:python${{ matrix.python_version }}
        function_dir: /function
